<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{1B4BBBAB-F990-4301-A760-278065E7D0B1}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>RhinoPlugInExcercise1</RootNamespace>
    <AssemblyName>RhinoPlugInExcercise1</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="RhinoCommon">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Rhino 6\System\rhinocommon.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eto">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Rhino 6\System\Eto.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rhino.UI">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Rhino 6\System\Rhino.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="BoxDynamic\Command\BoxDynamicDrawInteractionFactory.cs" />
    <Compile Include="BoxDynamic\Command\BoxDynamicParameters.cs" />
    <Compile Include="BoxDynamic\Command\CornerPtIteration.cs" />
    <Compile Include="BoxDynamic\Command\CornerPtIteration1.cs" />
    <Compile Include="BoxDynamic\Command\GetBoxDynamicAction.cs" />
    <Compile Include="BoxDynamic\Command\GetBoxDynamicIteration0.cs" />
    <Compile Include="BoxDynamic\Command\GetBoxDynamicIteration1V2.cs" />
    <Compile Include="BoxDynamic\Command\GetBoxDynamicIteration2.cs" />
    <Compile Include="BoxDynamic\Command\GetBoxDynamicIteration3.cs" />
    <Compile Include="BoxDynamic\Command\IGetBoxDynamicIteration0.cs" />
    <Compile Include="BoxDynamic\Command\IGetBoxDynamicIteration1.cs" />
    <Compile Include="BoxDynamic\Command\IGetBoxDynamicIteration2.cs" />
    <Compile Include="BoxDynamic\Command\IGetBoxDynamicIteration3.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\BaseViewModel.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\BoxCreation.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\BoxCreationV2.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\BoxDynamicDrawInteraction.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\BoxDynamicDrawInteractionIteration0.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\BoxDynamicDrawInteractionIteration1.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\BoxDynamicDrawInteractionIteration2.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\BoxDynamicDrawInteractionIteration3.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\DefaultDisplayMaterials.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\IBoxDynamicDrawInteraction.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\IDefaultDisplayMaterials.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\IDrawer.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\SelectedBrepFaceHoveredDrawer.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\DynamicInteraction\TypicalDrawer.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\MouseMoveInteractions\BoxDynamicMouseMoveInteractionV2.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Tools\EdgesFromFloorUpdateInfoGetter.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Actions\CloseEdit\FloorBoundaryCloseEditActionV4.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IEdgesFromFloorUpdateInfoGetter.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Tools\ClosedPlanarCurveAdditionBag.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Tools\CurveAdditionListenerV2.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Tools\ClosedPlanarCurveAdditionListener.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Actions\CloseEdit\FloorBoundaryCloseEditActionV3.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Actions\OpenEdit\FloorBoundaryOpenEditActionV2.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Actions\Create\FloorCreateByBoundaryActionOriginalV2.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Actions\Create\FloorCreateByBoundaryActionV3.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IClosedPlanarCurveAdditionBag.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IClosedPlanarCurveAdditionListener.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IFloorBoundaryCloseEditAction.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IFloorBoundaryOpenEditAction.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Commands\RcChangeFloorThickness.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Commands\RcFloorOpenEdit.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Commands\RcFloorCloseEdit.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\EditableRailingCreateActionV3.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\EditableRailingCreateActionV2.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\EditableRailingCreateActionV4.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\IRailingComponentIdsByNameFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\RailingComponentIdsByNameFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\OpenEdit\OpenEditRailingActionV2.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcCreateRailingV5.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcCreateRailingV4.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcCreateRailingV3.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Interfaces\IOpenEditRailingAction.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Interfaces\IRailingAssemblyId.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Interfaces\IRailingCloseEditAction.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\OpenEdit\OpenEditRailingAction.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\CloseEdit\CloseEditRailingAction.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcCloseEditRailing.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcCreateRailingV2.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Commands\RcOpenEditRailing.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\IRhBuildingComponentIdFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\IRhGeometryDoc.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\IRhinoObjectFilter.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailProfileCurveFilter.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RhBuildingComponentId.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\IBuildingComponentId.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\IRailingAssemblyIdFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\AssemblyComponentsToSessionAdder.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RhBuildingComponentIdFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RhiDisplayBuildingComponentId.cs" />
    <Compile Include="SweepObj\Commands\RcSweepObjV3.cs" />
    <Compile Include="SweepObj\Tools\AssemblyComponentsToSessionAdderV2Factory.cs" />
    <Compile Include="SweepObj\Tools\AssemblyIdV2Factory.cs" />
    <Compile Include="SweepObj\Tools\AssemblyIdV2.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailingAssemblyId.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailingAssemblyIdFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailingCompositionalElementNames.cs" />
    <Compile Include="SweepObj\Tools\ComponentsToRhinoGroupAdderV2.cs" />
    <Compile Include="SweepObj\Tools\ComponentsToRhinoGroupAdder.cs" />
    <Compile Include="SweepObj\Tools\IComponentsToRhinoGroupAdder.cs" />
    <Compile Include="SweepObj\Tools\RailingComponentsToSessionAdder.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailingComponentsToSessionAdderV3.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RhinoGetCustom.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RailsCurveAdditionBag.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Tools\RhinoRailingUpdateInfo.cs" />
    <Compile Include="SweepObj\Actions\BrepSweepsFactory.cs" />
    <Compile Include="EditModelCommands\CreateRailing\Actions\Create\EditableRailingCreateAction.cs" />
    <Compile Include="SweepObj\Actions\EditableSweepCreateActionFactory.cs" />
    <Compile Include="SweepObj\Interfaces\IEditableSweepCreateActionFactory.cs" />
    <Compile Include="SweepObj\Interfaces\IBrepSweepsFactory.cs" />
    <Compile Include="SweepObj\Interfaces\IComponentsToSessionAdder.cs" />
    <Compile Include="Tools\Id\CompositeObjId.cs" />
    <Compile Include="SweepObj\Tools\BuildingComponentsToSessionAdder.cs" />
    <Compile Include="SweepObj\Tools\GenericAssemblyComponentsToSessionAdder.cs" />
    <Compile Include="SweepObj\Tools\IAssemblyComponentsToSessionAdderFactory.cs" />
    <Compile Include="SweepObj\Interfaces\IEditableSweepCreateAction.cs" />
    <Compile Include="Tools\AssemblyIdFactory.cs" />
    <Compile Include="Tools\AssemblyIdList.cs" />
    <Compile Include="Tools\AssemblyTypeNames.cs" />
    <Compile Include="Tools\BrepFloorFactoryV2.cs" />
    <Compile Include="Tools\BrepFloorFactoryExt.cs" />
    <Compile Include="Tools\BrepFloorFactoryV5.cs" />
    <Compile Include="Tools\ExtrudeVectorGetter.cs" />
    <Compile Include="Tools\FloorBrepUpdateSubscriberV2.cs" />
    <Compile Include="Tools\EdgesSorter.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IEdgesSorter.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IFloorBrepUpdateSubscriber.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IFloorCreateByBoundaryAction.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Interfaces\IBrepFloorFactory.cs" />
    <Compile Include="EditModelCommands\CreateFloorByBoundary\Commands\RcCreateFloorByBoundary.cs" />
    <Compile Include="Interfaces\IBoxCreation.cs" />
    <Compile Include="Interfaces\IOffsetDistancesGetter.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\MouseMoveInteractions\IMouseMoveInteraction.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\OffDistanceViewModel.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\OffsetDistancesGetter.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\OffsetDistancesGetterV6.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\OffsetDistanceWindow.xaml.cs">
      <DependentUpon>OffsetDistanceWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="BoxDynamic\RelevantObjsGetterV2.cs" />
    <Compile Include="Interfaces\IPlaneDrawer.cs" />
    <Compile Include="BoxDynamic\PlaneDrawer.cs" />
    <Compile Include="BoxDynamic\RelevantClosestObjToViewCursorGetterFactory.cs" />
    <Compile Include="BoxDynamic\GetPointSubclass\GetBoxDynamic.cs" />
    <Compile Include="ArStudyOnCirclesAxes\GetCircleClosestPts.cs" />
    <Compile Include="BoxDynamic\Command\RcBoxDynamic.cs" />
    <Compile Include="Interfaces\IRelevantObjsGetter.cs" />
    <Compile Include="PullFace\DistanceBtwObjAndViewGetter.cs" />
    <Compile Include="PullFace\GetPointSubclass\IPullFaceCreation.cs" />
    <Compile Include="PullFace\GetPointSubclass\PullFaceCreation.cs" />
    <Compile Include="PullFace\Interactions\DynamicDrawInteratctions\PullFaceDynamicDrawInteraction.cs" />
    <Compile Include="PullFace\Interactions\DynamicDrawInteratctions\PullFaceDynamicDrawInteractionIteration1.cs" />
    <Compile Include="PullFace\FrameAlignHandler.cs" />
    <Compile Include="Interfaces\IFrameAlignHandler.cs" />
    <Compile Include="PullFace\Interactions\DynamicDrawInteratctions\PullFaceDynamicDrawInteractionIteration0.cs" />
    <Compile Include="PullFace\GetPointSubclass\ExtrusionCreation.cs" />
    <Compile Include="PullFace\Interactions\MouseMoveInteraction\PullFaceMouseMoveInteraction.cs" />
    <Compile Include="PullFace\PullFaceHandlers\BrepAdditionOrSubstractionChecker.cs" />
    <Compile Include="PullFace\PullFaceHandlers\BrepCombinerV2.cs" />
    <Compile Include="Interfaces\IBrepAdditionOrSubstractionChecker.cs" />
    <Compile Include="Interfaces\IBrepCombiner.cs" />
    <Compile Include="PullFace\PullFaceHandlers\PullFaceFromBrepHandlerV2.cs" />
    <Compile Include="PullFace\RcBrepFacesVisualizer.cs" />
    <Compile Include="PullFace\RelevantBrepFaceClosestToViewCursorGetterV3.cs" />
    <Compile Include="PushPullEdge\RcPushPullEdge.cs" />
    <Compile Include="RcCleanBrep\RcCleanBrep.cs" />
    <Compile Include="RcOpenByFileTxtCommand.cs" />
    <Compile Include="RcOpenCommand.cs" />
    <Compile Include="PullFace\BrepFaceGetter.cs" />
    <Compile Include="PullFace\BrepFaceGetterFactory.cs" />
    <Compile Include="Interfaces\IDistanceForObjAndViewGetter.cs" />
    <Compile Include="Interfaces\IRelevantBrepFaceClosestToViewCursorGetter.cs" />
    <Compile Include="Interfaces\IRelevantClosestObjToViewCursorGetter.cs" />
    <Compile Include="Interfaces\IBrepFaceToPullGetter.cs" />
    <Compile Include="PullFace\BrepCleaner.cs" />
    <Compile Include="Interfaces\IBrepCleaner.cs" />
    <Compile Include="Interfaces\IPullFaceFromBrepHandler.cs" />
    <Compile Include="Interfaces\IPullFaceFromExtrusionHandler.cs" />
    <Compile Include="PullFace\GetPointSubclass\PullFaceDynamic.cs" />
    <Compile Include="PullFace\Command\RcPullFace.cs" />
    <Compile Include="Interfaces\IFilter.cs" />
    <Compile Include="PullFace\PullFaceHandlers\PullFaceFromExtrusionHandler.cs" />
    <Compile Include="PullFace\RelevantClosestObjToViewCursorGetter.cs" />
    <Compile Include="RcTrimPolyline\GetTrimPolylineV3.cs" />
    <Compile Include="RcTrimPolyline\ILineSelectedToTrimGetter.cs" />
    <Compile Include="RcTrimPolyline\IPolylineTrimHandler.cs" />
    <Compile Include="RcTrimPolyline\IPolylineTrimInfo.cs" />
    <Compile Include="RcTrimPolyline\IPolylineTrimInfoGetter.cs" />
    <Compile Include="RcTrimPolyline\IPolylineTrimInfoV2.cs" />
    <Compile Include="RcTrimPolyline\LineSelectedToTrimGetter.cs" />
    <Compile Include="RcTrimPolyline\PolylineCreation.cs" />
    <Compile Include="RcTrimPolyline\PolylineTrimHandlerV3.cs" />
    <Compile Include="RcTrimPolyline\PolylineTrimInfo.cs" />
    <Compile Include="RcTrimPolyline\PolylineTrimInfoGetter.cs" />
    <Compile Include="RcTrimPolyline\RcTrimPolyline.cs" />
    <Compile Include="SampleCylinderDraw\GumballCylinderGetPointV2.cs" />
    <Compile Include="SampleCylinderDraw\GumballCylinderCommandV2.cs" />
    <Compile Include="SampleCylinderDraw\GumballCylinderV2.cs" />
    <Compile Include="SelectObjects\ObjGetterV2.cs" />
    <Compile Include="RcFilletInteractive\FilletInteractiveRhAction.cs" />
    <Compile Include="RcFilletInteractive\GetArcFilletDynamic.cs" />
    <Compile Include="ArStudyOnCirclesAxes\GetCircleV2.cs" />
    <Compile Include="ArStudyOnCirclesAxes\GetCircle.cs" />
    <Compile Include="ArStudyOnCirclesAxes\ArStudyOnCirclesAxes.cs" />
    <Compile Include="RcFilletInteractive\RcFilletInteractive.cs" />
    <Compile Include="SelectObjects\RcSelectExtrusions.cs" />
    <Compile Include="SelectObjects\RcSelectSurfaces.cs" />
    <Compile Include="SelectObjects\RcSelectPoints.cs" />
    <Compile Include="SelectObjects\RcSelectBreps.cs" />
    <Compile Include="SelectObjects\RcSelectCurves.cs" />
    <Compile Include="RcTrim\RcTrim.cs" />
    <Compile Include="RcTrim\TrimRcAction.cs" />
    <Compile Include="RhinoPlugInExcercise1PlugIn.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="SelectObjects\SelectionFilters\SurfaceSelectionFilter.cs" />
    <Compile Include="SelectObjects\TypicalSelectionFilter.cs" />
    <Compile Include="SweepObj\SweepObjsGraph.cs" />
    <Compile Include="Tools\DI.cs" />
    <Compile Include="Tools\DocManager.cs" />
    <Compile Include="Tools\FloorComponentId.cs" />
    <Compile Include="Tools\GenericAssemblyId.cs" />
    <Compile Include="Tools\IAssemblyIdFactory.cs" />
    <Compile Include="Tools\IAssemblyIdList.cs" />
    <Compile Include="Tools\IBrepFloorFactoryV2.cs" />
    <Compile Include="Tools\Id\CompositeObjIdFactoryForRailing.cs" />
    <Compile Include="Tools\Id\CompositionalIdV2.cs" />
    <Compile Include="Tools\Id\CompositionalId.cs" />
    <Compile Include="Tools\Id\ConstituentId.cs" />
    <Compile Include="Tools\IRhinoObjChangeManager.cs" />
    <Compile Include="Tools\IRailingAssemblyBrepUpdateSubscriber.cs" />
    <Compile Include="Tools\ISweepAssemblyIdFactory.cs" />
    <Compile Include="Tools\RailingUpdateInfos.cs" />
    <Compile Include="Tools\RhinoAppLogWriter.cs" />
    <Compile Include="Tools\RhinoDoc.cs" />
    <Compile Include="Tools\RhinoFloorUpdateInfo.cs" />
    <Compile Include="Tools\RhinoObjChangeManager.cs" />
    <Compile Include="Tools\RailingAssemblyBrepUpdateSubscriber.cs" />
    <Compile Include="Tools\SweepAssemblyId.cs" />
    <Compile Include="Tools\IoCConfiguration.cs" />
    <Compile Include="Tools\SessionDoc.cs" />
    <Compile Include="Tools\SweepAssemblyIdFactory.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\plugin-utility.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DLFramework\DL.Framework.csproj">
      <Project>{2FB7026B-5A47-4FCD-AA2E-F720162EE1F0}</Project>
      <Name>DL.Framework</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ReportUtilityLib\ReportUtilityLib.csproj">
      <Project>{C7432115-1B0C-4DF1-A118-59E6BAD49B0E}</Project>
      <Name>ReportUtilityLib</Name>
    </ProjectReference>
    <ProjectReference Include="..\DL.RhinoExcercise1.Core\DL.RhinoExcercise1.Core.csproj">
      <Project>{dcadb1c9-8783-4f33-b6f8-d10f4d72d53d}</Project>
      <Name>DL.RhinoExcercise1.Core</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Page Include="BoxDynamic\GetPointSubclass\OffsetDistanceWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="PullFace\Interactions\MouseDownInteractions\" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
  <PropertyGroup>
    <PostBuildEvent>Copy "$(TargetPath)" "$(TargetDir)$(ProjectName).rhp"
Erase "$(TargetPath)"</PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup>
    <FallbackCulture>en-US</FallbackCulture>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <StartProgram>C:\Program Files\Rhino 6\System\Rhino.exe</StartProgram>
    <StartArguments>
    </StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>
</Project>